[package]
authors = ["jD91mZM2 <me@krake.one>"]
description = "xautolock rewrite in Rust, with a few extra features"
license-file = "LICENSE"
name = "xidlehook"
readme = "README.md"
repository = "https://github.com/jD91mZM2/xidlehook"
version = "0.4.6"

[dependencies]
clap = "2.29.2"
failure = "0.1.1"

[dependencies.ctrlc]
features = ["termination"]
optional = true
version = "3.1.0"

[dependencies.futures]
optional = true
version = "0.1.18"

[dependencies.libpulse-sys]
optional = true
version = "1.0.1"

[dependencies.tokio-core]
optional = true
version = "0.1.12"

[dependencies.tokio-io]
optional = true
version = "0.1.4"

[dependencies.tokio-signal]
optional = true
version = "0.1.5"

[dependencies.tokio-uds]
optional = true
version = "0.1.7"

[dependencies.x11]
features = ["xlib", "xss"]
version = "2.17.2"

[features]
default = ["pulse"]
pulse = ["tokio", "libpulse-sys"]
tokio = ["ctrlc", "futures", "tokio-core", "tokio-io", "tokio-signal", "tokio-uds"]
