[package]
authors = ["jD91mZM2 <me@krake.one>"]
description = "xautolock rewrite in Rust, with a few extra features"
license-file = "LICENSE"
name = "xidlehook"
readme = "README.md"
repository = "https://github.com/jD91mZM2/xidlehook"
version = "0.4.6"

[dependencies]
clap = "2.29.2"
failure = "0.1.1"
mio = "0.6.14"
nix = "0.10.0"

[dependencies.libpulse-sys]
optional = true
version = "1.0.1"

[dependencies.x11]
features = ["xlib", "xss"]
version = "2.17.2"

[features]
default = ["pulse"]
pulse = ["libpulse-sys"]
