[package]
authors = ["jD91mZM2 <me@krake.one>"]
description = "xautolock rewrite in Rust, with a few extra features"
license-file = "LICENSE"
name = "xidlehook"
version = "0.1.1"
[dependencies]
clap = "2.29.2"

[dependencies.x11]
features = ["xlib", "xss"]
version = "2.17.2"
